name: "Multi event pipeline / workflow"   # Name of the pipeline

on:
    push: # Event: Whenever a push is made to the repository on the master branch
        branches:
            - master
            - test
    # schedule:
    #     - cron: "0 10 * * 2,4"
    pull_request: # Event: Whenever a pull request is make to the repository
        branches:
            - master 
        types:
            - closed
            - opened
    workflow_dispatch: # Manual trigger - no branch specification needed



jobs:
    on-push: # Job 1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on master/test push"  # Step 1
              run: echo "Runnning on master/test push" 

    on-pull-request: # Job 2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
           - name: "Running on pull request" # Step 1
             run: echo "Running on pull request"
    
    on-pull-request-opened:
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        runs-on: ubuntu-latest
        steps:
            - name: 'Running on pull request opened'
              run: echo "Running on pull request opened"
            
    on-pull-request-closed:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: 'Running on pull request closed'
              run: echo "Running on pull request closed"
    
    on-workflow-dispatch: # Job 3
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on workflow dispatch" # Step 1
              run: echo "Running on workflow dispatch"
    
    on-schedule: # Job 4
        if: github.event_name == 'schedule'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on schedule" # Step 1
              run: echo "running on schedule"